"""Add chat meta table

Revision ID: chat_meta_table
Revises: db_query_history
Create Date: 2023-11-15 10:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mysql import JSON


# revision identifiers, used by Alembic.
revision = "chat_meta_table"
down_revision = "db_query_history"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_meta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=256), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"]),
        sa.PrimaryKeyConstraint("id")
    )
    
    # 创建索引
    op.create_index(
        "ix_chat_meta_chat_id", 
        "chat_meta", 
        ["chat_id"], 
        unique=False
    )
    op.create_index(
        "ix_chat_meta_key", 
        "chat_meta", 
        ["key"], 
        unique=False
    )
    op.create_index(
        "ix_chat_meta_chat_id_key", 
        "chat_meta", 
        ["chat_id", "key"], 
        unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chat_meta_chat_id_key", table_name="chat_meta")
    op.drop_index("ix_chat_meta_key", table_name="chat_meta")
    op.drop_index("ix_chat_meta_chat_id", table_name="chat_meta")
    op.drop_table("chat_meta")
    # ### end Alembic commands ### 