"""Add database query history table

Revision ID: db_query_history
Revises: c7f016a904c1
Create Date: 2023-11-10 14:30:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mysql import JSON


# revision identifiers, used by Alembic.
revision = "db_query_history"
down_revision = "c7f016a904c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "database_query_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.UUID(), nullable=False),
        sa.Column("chat_message_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("connection_id", sa.Integer(), nullable=False),
        sa.Column("connection_name", sa.String(length=256), nullable=False),
        sa.Column("database_type", sa.String(length=50), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("is_successful", sa.Boolean(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("result_summary", JSON(), nullable=True),
        sa.Column("result_sample", JSON(), nullable=True),
        sa.Column("execution_time_ms", sa.Integer(), nullable=True),
        sa.Column("rows_returned", sa.Integer(), nullable=True),
        sa.Column("routing_score", sa.Float(), nullable=True),
        sa.Column("routing_context", JSON(), nullable=True),
        sa.Column("user_feedback", sa.Integer(), nullable=True),
        sa.Column("user_feedback_comments", sa.Text(), nullable=True),
        sa.Column("meta", JSON(), nullable=True),
        sa.Column("executed_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"]),
        sa.ForeignKeyConstraint(["chat_message_id"], ["chat_messages.id"]),
        sa.ForeignKeyConstraint(["connection_id"], ["database_connections.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_database_query_history_chat_id", 
        "database_query_history", 
        ["chat_id"], 
        unique=False
    )
    op.create_index(
        "ix_database_query_history_chat_message_id", 
        "database_query_history", 
        ["chat_message_id"], 
        unique=False
    )
    op.create_index(
        "ix_database_query_history_connection_id", 
        "database_query_history", 
        ["connection_id"], 
        unique=False
    )
    op.create_index(
        "ix_database_query_history_user_id", 
        "database_query_history", 
        ["user_id"], 
        unique=False
    )
    op.create_index(
        "ix_db_query_history_chat_id_executed_at", 
        "database_query_history", 
        ["chat_id", "executed_at"], 
        unique=False
    )
    op.create_index(
        "ix_db_query_history_connection_id_executed_at", 
        "database_query_history", 
        ["connection_id", "executed_at"], 
        unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_db_query_history_connection_id_executed_at", 
        table_name="database_query_history"
    )
    op.drop_index(
        "ix_db_query_history_chat_id_executed_at", 
        table_name="database_query_history"
    )
    op.drop_index(
        "ix_database_query_history_user_id", 
        table_name="database_query_history"
    )
    op.drop_index(
        "ix_database_query_history_connection_id", 
        table_name="database_query_history"
    )
    op.drop_index(
        "ix_database_query_history_chat_message_id", 
        table_name="database_query_history"
    )
    op.drop_index(
        "ix_database_query_history_chat_id", 
        table_name="database_query_history"
    )
    op.drop_table("database_query_history")
    # ### end Alembic commands ### 